### ISSUE TITLE
Total Faturado Retornando 0,00

### ISSUE THREAD

**Issue by pauloneda** [robmachado/teste#1]
\app\dados.php Linha 174
from                 $totFat += $valorFat;

to                     $totFat += $vNF;

**Comment by robmachado** [comment]
Não faço a menor ideia do que você está falando !!!!

**Comment by robmachado** [comment]
Negativo.... nem sempre o valor da NF é um Faturamento ... se eu estou devolvendo uma mercadoria não tem ICMS então não é um faturamento ... tá certo que também não está muito correto pois o valor do faturamento deve vir da tag faturamento. Assim que tiver um tempo dou uma outra olhada mas esse aplicativo é apenas um exemplo de uso não tem a intensão de ser usado realmente. (Pelo menos por enquanto)
