### ISSUE TITLE
Atualização 

### ISSUE THREAD

**Issue by ezequiel88** [robmachado/teste#12]
Recebo esses avisos quando na instalação. O aplicativo foi descontinuado?

Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.
Package nfephp-org/nfephp is abandoned, you should avoid using it. Use nfephp-org/sped-nfe instead.

Quando tento executar recebo os avisos abaixo:

Fatal error: Uncaught NFePHP\Common\Exception\InvalidArgumentException: O arquivo indicado não foi localizado!! ../config/config.json in C:\wamp\www\teste\vendor\nfephp-org\nfephp\libs\Common\Files\FilesFolders.php on line 257
--

Grato.

**Comment by robmachado** [comment]
Então meu amigo não mexo nisso a mais de 3 anos muita água já rolou !! E esse exemplo não é mais funcional, quando eu tiver algum tempo de sobra verei se vale a pena manter isso ou remover.
