### ISSUE TITLE
Não houve retorno do CURL

### ISSUE THREAD

**Issue by fernandoantunes** [robmachado/teste#6]
Foi seguido os passos corretos para utilizar a LIB NFePHP, após executar o projeto de teste, retornou a seguinte mensagem:

Não houve retorno do Curl. SSL: Can't load the certificate "/Users/fernandoantunes/www/teste/publico/certs/24285431000100_certKEY.pem" and its private key: OSStatus -25299 

Existe alguma outra configuração a ser feita? ou o padrão que está no XML está desatualizado? já obteve esta exceção?

**Comment by masakik** [comment]
Você deu permissão de escrita para o apache na pasta certs?

2016-05-18 20:43 GMT-03:00 Fernando Antunes notifications@github.com:

**Comment by fernandoantunes** [comment]
Dei a permissão de escrita, em pesquisas descobri que no MAC OS o CURL vem com o SSL desabilitado mesmo forçando a instalação, preciso estudar uma forma de resolver esta questão, pois utilizo ele para desenvolvimento, subi em um servidor LINUX e rodou normalmente.

Este exemplo de teste apenas lista as NFe? no caso se eu precisar emitir algumas NFe no ambiente de homologação devo construir o script ou já tem algum para executar?

**Comment by guilhermelimpo** [comment]
Encontrei em alguns fóruns dizendo que o MAC OS precisa que utilize .p12 invés do .pem.

Alguém conseguiu resolver esse problema?
